const en = {
  translation: {
    
    //Màn hình khởi đầu
    landing: "Fewcha Wallet",
    decs_landing: "Hope into Aptos' world with Fewcha",
    create_landing: "Create Your Wallet",
    import_landing: "Import your Security Phrase",
    import_pk_landing: "Import your Private Key",

    //General––Text––Buttons––Terms
    fewcha_version: "Prototype Version",
    button_back: "Back",
    term: "I have agreed to the ",
    term2: "Term of Uses",
    back: "Back",
    confirm: "Confirm",
    create: "Create",
    finish: "Finish",
    import: "Import",
    save_note: "Please save your Secret Recovery Phrase to the safe place",
    note: "Please save your Security Phrase to the safe place, do not share it to anyone",
    note2: "Warning:",
    note3: "DO NOT ",
    note4: "share your Private Key or Recovery Phrase to anyone. Security Phrase and Private Key is the",
    note5: "ONLY",
    note6: "way to recover your wallet.",
    save: "I have saved my Security/Private Key to the safe place",
    save_button: "Save",
    saverpc: "Add this RPC Network",
    continue: "Continue",
    unlock_wallet: "Unlock Wallet",
    address: "Address",
    wallet_address: "Wallet Address",
    current_acc: "Current Account",
    create_security_phrase: "Create Security Recovery Phrase",
    account: "Accounts",
    add: "Add more account",
    add_button: "Add",
    cancel: "Cancel",
    create_desc: "Create new wallet account from your Security Phrase",
    unsupport: "Upsupported feature",
    fav_acc: "Favorite Accounts",
    import_success: "Sucsessfully Imported",
    unvalid: "Private Key is unvalid",
    connect: "Connect",
    address_book: "Your contacts",
    custom: "Custom",
    addressbook_add: "Custom your contacts",
    addressbook_title: "Address Book",
    addressbook_desc: "Allow you to add more contacts",
    add_contact: "Add new contacts",
    add_network: "Add RPC Network",
    add_contact_desc: "Allow you to add new contacts",
    empty: "It's empty",
    asktoconfirm: "Please confirm before delete this address",
    name_text: "Name",
    success: "Success",
    status: "Status",
    send_status_failed: "Failed",
    transaction: "Your transactions",
    change : "Change",
    close: "Close",
    swap_title: "Built-in exchange",
    delete_button: "Delete",
    confirm_connect_delete: "Confirm to disconnect this website",
    disconnect: "Disconnect",
    name: "Name",
    custom_title: "Custom your RPC Network",
    rpcname: "RPC Name",
    rpc_list: "RPC Networks",

    //–––––––––––//


    //Connection Requirements
    text_connect: "Fewcha would like to",
    checkbox: "View your Balance",
    checkbox2: "Activities",
    checkbox3: "Request and perform your transactions",
    remind: "Only connect to the website you are trusted",

    //Màn hình tạo account > This also use for password notification requremients
    text_create: "Create Account",
    text_create1: "Create your account",
    text_pwd: "Enter your password",
    text_unlock: "Create password to unlock your wallet",
    text_confirm: "Please enter your password",
    text_confirm1: "Create new password",
    text_confirm2: "Please fill to continue",
    text_confirm3: "Confirm your password",
    text_confirm4: "Please re-confirm your password",
    text_confirm5: "Please re-confirm your password to continue",
    text_confirm6: "Enter new password",
    title_pwd: "Password",
    message: "Import your Recovery Phrase to continue",
    sec_phrase: "Security Recovery Phrase",
    unmatch: "Your confirm password isn't match, please try again",
    send: "SEND",
    receive: "Receive",
    coming: "This feature will come along with next updates",
    news: "Fewcha newspaper",
    pwd_require: "Password is required!",
    pk_import: "Import wallet from Private Key",
    import_placeholder: "Import your Private Key",
    notfound: "Not Found!",
    wrongpwd: "Wrong Password",  
    text_changepwd: "Change Password",
    enter_currentpwd: "Enter your current password",
    re_confirmpwd: "Re-confirm your new password",
    confirmnewpwd: "Confirm new password",
    change_locktimer: "Lock-time modify",
    ui_settings: "UI Settings",
    theme: "Theme",
    lngdisplay: "Language Display",
    coming2: "On development",
    security: "Security",
    trusted: "Trusted Website",
    text_theme: "Change your theme",
    trusted_desc: "This feature show your connected website.",
    pwd_locktime_config: "Config password and lock-timer",
    rpc_title: "RPC Network",
    rpc_text: "Custom RPC Network",
    rpc_desc: "Allow you to add other RPC Network",
    version2: "Version",
    caution: "Cautions",
    reveal_confirm: "Confirm to reveal your Security Phrase",
    reveal_confirm_text: "NEVER share your Security Phrase",
    reveal_confirm_text2: "If someone has your Security Phrase, they will have full access to your wallet.",
    enter_reveal: "Enter password to reveal",
    sec_phrase2: "Reveal Recovery Phrase",
    export_mnemonic: "Export your Mnemonic (BIP39) phrase",
    security_req: "Security Phrase is required!",
    unmatchphrase: "Security Phrase did not match",
    reset_confirm: "Confirm to reset your wallet",
    reset_confirm2: "Be careful. You",
    reset_confirm3: "CAN NOT",
    reset_confirm4: "Undo your action, the current",
    reset_confirm5: "Secret Recovery Phrase",
    reset_confirm6: "will be removed.",
    sec_placeholder: "Enter your Security Phrase",
    resetall_text: "Reset all",
    resetall_desc: "Reset your wallet extension",





    //–––––––––––//

    //Màn hình finish khi tạo account

    finish_text: "You are all done ;)",
    twitter: "Follow us on Twitter:",
    discord: "Hope into Fewcha Discord:",
    medium: "Read our Medium Blog:",
    telegram: "Follow Fewcha on Telegram:",

    //Màn hình ImportMnemonic
    mn_create: "Import Mnemonic and create password",

    //Màn hình Import Private Key
    pk_create: "Import Private Key and create password",
    pk_error: "Enter your Private Key to continue",
  },
};

export default en;
